# Use root/example as user/password credentials
version: '3.9'

services:

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5a87sd8fsdfsEjwo
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
        #    ports:
        #      - 33060:33060

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
        
  projectik:
    build: ./flask
    restart: always
    ports:
      - 5000:5000

        #  nginx:
        #    image: nginx
        #    volumes:
        #      - ./nginx/etc/conf.d:/etc/nginx/conf.d
        #    ports:
        #      - 8000:8000
        #    command: [nginx-debug, '-g', 'daemon off;']

        
        
